<?php

/**
 * @file
 * ya_turbo module file.
 */


/**
 * Implements hook_menu().
 */

function ya_turbo_menu() {
  $items['ya.turbo.xml'] = array(
    'page callback' => 'turbo_page',
    'access callback' => TRUE,
    'type' => MENU_CALLBACK,
  );

  return $items;
}


/**
 * Callback to display rss file.
 */
function turbo_page() {
  $content = _turbo_get_content();
  header('Content-type: application/xml; charset=UTF-8');

  echo $content;

  exit;
}

/**
 * Helper function to get the content of the rss file.
 */
function _turbo_get_content() {
  $YML_t = '';
  $YML = "<?xml version=\"1.0\" encoding=\"UTF-8\"?>
  <rss xmlns:yandex=\"http://news.yandex.ru\"
       xmlns:media=\"http://search.yahoo.com/mrss/\"
       xmlns:turbo=\"http://turbo.yandex.ru\"
       version=\"2.0\">
      <channel>
          <!-- Информация о сайте-источнике -->
          <title>Ribbla digital агентство</title>
          <link>https://ribbla.com/</link>
          <description>Ribbla digital агентство</description>
          <language>ru</language>";
    
        $output = node_load_multiple(array(), array('type'=> array('blog', 'job', 'comments', 'project', 'certificates', 'employees', 'solution', 'page'), 'status' => 1));
        $output = node_view_multiple($output, 'teaser');
                
        foreach ($output['nodes'] as $node) {
          if ($node['#node']) {

                  $YML .= "
                  <item turbo=\"true\">
                    <link>https://ribbla.com/node/".$node['#node']->nid."</link>
                    <turbo:source>https://ribbla.com/node/".$node['#node']->nid."</turbo:source>
                    <turbo:topic>".$node['#node']->title."</turbo:topic>
                    <pubDate>".date("r", $node['#node']->created)."</pubDate>
                    <turbo:content> <![CDATA[<header><h1>Ribbla digital агентство</h1><h2>".$node['#node']->title."</h2></header>".  render($node) ." ]]></turbo:content>
                  </item>";

          }
        }


$terms = db_query("SELECT tid FROM {taxonomy_term_data} td  WHERE vid = :vid", array(':vid' => 6));
$items = array();
foreach ($terms as $term) {
  $items[] = ($term->tid);
}
//var_dump($items);

//$items = [38, 39, 40, 41, 42, 43];

foreach ($items as $tid) {

  $result = taxonomy_term_load($tid);
   $YML_t .= "
                  <item turbo=\"true\">
                    <link>https://ribbla.com/taxonomy/term/".$result->tid."</link>
                    <turbo:source>https://ribbla.com/taxonomy/term/".$result->tid."</turbo:source>
                    <turbo:topic>".$result->name."</turbo:topic>
                    <turbo:content> 
                    <![CDATA[
                    <header><h1>Ribbla digital агентство</h1>
                    <h2>".$result->title."</h2>
                    </header>".  $result->title.$result->description ." ]]></turbo:content>
                  </item>";
 }

return $YML.$YML_t . '</channel></rss>';
}
